### ISSUE TITLE
Will not open in KiCad 5.1.9 Stable (latest stable)

### ISSUE THREAD

**Issue by critter42** [MarkR42/malenki-nano#1]
Attempts to open malenki-nanox.kicad_pcb in KiCad 5.1.9 Stable release results in error:

KiCad was unable to open this file, as it was created with
a more recent version than the one you are running

To open it, you'll need to upgrade KiCad to a more recent version

Date of KiCad version required (or newer): 05/18/20

Looking at the file header:
(kicad_pcb (version 20200518) (host pcbnew "5.99.0-unknown-60915fb~101~ubuntu18.04.1")

Can this be released in the current stable version of KiCad? 5.99 appears to be an unstable version and I am having problems trying to compile it.

**Comment by MarkR42** [comment]
No, I'm afraid you'll need to use the unstable version of Kicad, or wait until 6.0 is released.

**Comment by critter42** [comment]
Yeah, I found their FAQ about that after I posted it. I'll go ahead and close this. After a day of working through dependency hell and an 8 hour compile, I got the latest nightly to build and was able to open the file! :)
