### ISSUE TITLE
3s Support?

### ISSUE THREAD

**Issue by cmlarsen** [MarkR42/malenki-nano#2]
I love the Malenki Nano, what in the design is limiting it to 2s?  It would be a nearly perfect US Ant Weight (1lb) receiver/esc solution, but for the 1 pound class, 3s is nearly require3d to be competitive at a lot of events.

**Comment by cmlarsen** [comment]
It looks like the `DRV8837` supports up to 12v.  would the Malenki smoke if I ran it at 3s stepped down to 12v with a buck?

(But I know absolutely nothing about circuit design, I was just poking around and noticed that)

**Comment by MarkR42** [comment]
Well the DRV8837 has 12V as its absolute maximum rating and a fully charged 3S pack is 12.6V so it's not ideal, I would feel unhappy about running it at that level. I have heard of some people running existing Malenki-Nanos on 3S, and it usually works ok for a short time, but not a great idea.

**Comment by MarkR42** [comment]
Oh yeah if you add an external regulator to regulate the voltage down to about 9V, the Malenki would be fine. But that's extra equipment.

**Comment by cmlarsen** [comment]
Would heat sinking the DRV8837s help run it at say...11v? (lots of tiny adjustable bucks)

**Comment by MarkR42** [comment]
I don't worry about heat killing them, I think they have thermal protection built-in. I think it's more likely that voltage spikes kill the internals. But I don't really know - I see very few dead drv chips.

**Comment by cmlarsen** [comment]
Closing this as the Malenki Nano HV (in beta) solves this proble.
