### ISSUE TITLE
Is 1616 version of hardware safe to use?

### ISSUE THREAD

**Issue by mattinglot** [MarkR42/malenki-nano#3]
Hey Mark,

Love the project and plan to try to build a few of these for myself and maybe even hack away at the 3S problem. 

But at the moment I can't find 817 or 1617 chips in stock, but I can find 1616.

Is the 1616 hardware tested and safe to use? The documentation claims anything other than "malenki-nanox" is experimental. Trying to avoid risking a PCB run that isn't supported.

Thanks.

**Comment by MarkR42** [comment]
Yes it seems to be working absolutely fine!

We have shipped many units with the attiny1616 mcu and they are working perfectly. There have been some minor manufacturing hiccups due to the chip being smaller pitch (0.4mm) - I would recommend using ENIG finish for the PCBs.

**Comment by MarkR42** [comment]
Your comment basically noticed that there are few 817 or 1617 in stock, that's why I did a slight redesign for the attiny1616. The firmware is more or less identical, differences are handled in #if statements. I think I did one pin swap.

**Comment by mattinglot** [comment]
Thanks I appreciate that info! Will give it a try.

**Comment by mattinglot** [comment]
Thanks so much Mark for the info and the tip on the PCB manufacturer. I've ordered some components including the 1616s and look forward to experimenting with the ESC.

**Comment by MarkR42** [comment]
Question answered
