### ISSUE TITLE
Obtaining the PCB Antenna

### ISSUE THREAD

**Issue by mattinglot** [MarkR42/malenki-nano#4]
Having trouble figuring out the PCB Antenna piece and wondering what the secret here is.

As far as I can tell that's not part of the main PCB? At least I can't find it in KiCad. 

- Is there a separate project file for this? Or a place to source it?
- How does it get attached to the main PCB?

Thanks and apologies if I'm missing something obvious.

Edit: 
Looking closer at a photo of the production product, it seems like you're not just using the A7105 chip but the whole module? Do you have a link where to source the correct part?

For greater clarity here is what I see in KiCad
https://capture.dropbox.com/fnqKQ7R3vsRxjTnc

VS 
https://shop.bristolbotbuilders.com/product/malenki/

**Comment by MarkR42** [comment]
Hi,

I haven't 3d-modelled the radio module.

The radio module is commonly known as "MD7105-SY" and is widely available (just now) on Aliexpress. I haven't found a more reliable vendor of them yet.

Some of the more recent ones use the A7106 chip which seems to be totally compatible.

**Comment by mattinglot** [comment]
Thanks. Will order one of these then. I totally thought at first that your PCB had the antenna and all the parts on it, hence the confusion. Using a module that's got all that built in makes way more sense. Appreciate the help (again).
